{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyyaml==5.1 in /opt/homebrew/lib/python3.10/site-packages (5.1)\n",
      "fatal: le chemin de destination 'detectron2' existe déjà et n'est pas un répertoire vide.\n",
      "Requirement already satisfied: Pillow>=7.1 in /opt/homebrew/lib/python3.10/site-packages (9.2.0)\n",
      "Requirement already satisfied: matplotlib in /opt/homebrew/lib/python3.10/site-packages (3.6.1)\n",
      "Requirement already satisfied: pycocotools>=2.0.2 in /opt/homebrew/lib/python3.10/site-packages (2.0.6)\n",
      "Requirement already satisfied: termcolor>=1.1 in /opt/homebrew/lib/python3.10/site-packages (2.1.1)\n",
      "Requirement already satisfied: yacs>=0.1.8 in /opt/homebrew/lib/python3.10/site-packages (0.1.8)\n",
      "Requirement already satisfied: tabulate in /opt/homebrew/lib/python3.10/site-packages (0.9.0)\n",
      "Requirement already satisfied: cloudpickle in /opt/homebrew/lib/python3.10/site-packages (2.2.1)\n",
      "Requirement already satisfied: tqdm>4.29.0 in /opt/homebrew/lib/python3.10/site-packages (4.64.1)\n",
      "Requirement already satisfied: tensorboard in /opt/homebrew/lib/python3.10/site-packages (2.12.0)\n",
      "Requirement already satisfied: fvcore<0.1.6,>=0.1.5 in /opt/homebrew/lib/python3.10/site-packages (0.1.5.post20221221)\n",
      "Requirement already satisfied: iopath<0.1.10,>=0.1.7 in /opt/homebrew/lib/python3.10/site-packages (0.1.9)\n",
      "Requirement already satisfied: omegaconf>=2.1 in /opt/homebrew/lib/python3.10/site-packages (2.3.0)\n",
      "Requirement already satisfied: hydra-core>=1.1 in /opt/homebrew/lib/python3.10/site-packages (1.3.2)\n",
      "Requirement already satisfied: black in /opt/homebrew/lib/python3.10/site-packages (23.1.0)\n",
      "Requirement already satisfied: packaging in /opt/homebrew/lib/python3.10/site-packages (23.0)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/lib/python3.10/site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/homebrew/lib/python3.10/site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/lib/python3.10/site-packages (from matplotlib) (4.37.4)\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in /Users/gabrielfiastre/Library/Python/3.10/lib/python/site-packages (from matplotlib) (3.0.9)\n",
      "Requirement already satisfied: numpy>=1.19 in /opt/homebrew/lib/python3.10/site-packages (from matplotlib) (1.23.3)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/gabrielfiastre/Library/Python/3.10/lib/python/site-packages (from matplotlib) (2.8.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /opt/homebrew/lib/python3.10/site-packages (from matplotlib) (1.0.5)\n",
      "Requirement already satisfied: PyYAML in /opt/homebrew/lib/python3.10/site-packages (from yacs>=0.1.8) (5.1)\n",
      "Requirement already satisfied: absl-py>=0.4 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (1.4.0)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (2.28.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (2.2.2)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (0.7.0)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (1.8.1)\n",
      "Requirement already satisfied: wheel>=0.26 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (0.38.4)\n",
      "Requirement already satisfied: setuptools>=41.0.0 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (65.6.3)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (3.4.1)\n",
      "Requirement already satisfied: protobuf>=3.19.6 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (3.19.6)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (2.16.2)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (0.4.6)\n",
      "Requirement already satisfied: grpcio>=1.48.2 in /opt/homebrew/lib/python3.10/site-packages (from tensorboard) (1.51.3)\n",
      "Requirement already satisfied: portalocker in /opt/homebrew/lib/python3.10/site-packages (from iopath<0.1.10,>=0.1.7) (2.7.0)\n",
      "Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/homebrew/lib/python3.10/site-packages (from omegaconf>=2.1) (4.9.3)\n",
      "Requirement already satisfied: mypy-extensions>=0.4.3 in /opt/homebrew/lib/python3.10/site-packages (from black) (1.0.0)\n",
      "Requirement already satisfied: click>=8.0.0 in /opt/homebrew/lib/python3.10/site-packages (from black) (8.1.3)\n",
      "Requirement already satisfied: platformdirs>=2 in /opt/homebrew/lib/python3.10/site-packages (from black) (2.5.4)\n",
      "Requirement already satisfied: tomli>=1.1.0 in /opt/homebrew/lib/python3.10/site-packages (from black) (2.0.1)\n",
      "Requirement already satisfied: pathspec>=0.9.0 in /opt/homebrew/lib/python3.10/site-packages (from black) (0.11.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /Users/gabrielfiastre/Library/Python/3.10/lib/python/site-packages (from google-auth<3,>=1.6.3->tensorboard) (1.16.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/homebrew/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (0.2.8)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/homebrew/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (5.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/homebrew/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/homebrew/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard) (1.3.1)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /opt/homebrew/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (2.1.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (1.26.12)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard) (2022.9.24)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/gabrielfiastre/Library/Python/3.10/lib/python/site-packages (from werkzeug>=1.0.1->tensorboard) (2.1.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/homebrew/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/homebrew/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard) (3.2.2)\n"
     ]
    }
   ],
   "source": [
    "# ALWAYS RUN\n",
    "\n",
    "import sys, os, distutils.core\n",
    "\n",
    "\n",
    "# INSTALL detectron 2 \n",
    "!python3 -m pip install pyyaml==5.1\n",
    "# Note: This is a faster way to install detectron2 in Colab, but it does not include all functionalities.\n",
    "# See https://detectron2.readthedocs.io/tutorials/install.html for full installation instructions\n",
    "!git clone 'https://github.com/facebookresearch/detectron2'\n",
    "dist = distutils.core.run_setup(\"./detectron2/setup.py\")\n",
    "!python3 -m pip install {' '.join([f\"'{x}'\" for x in dist.install_requires])}\n",
    "\n",
    "\n",
    "\n",
    "#### ONLY FIRST TIME\n",
    "\n",
    "# Properly install detectron2. (Please do not install twice in both ways)\n",
    "#!python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'\n",
    "\n",
    "\n",
    "sys.path.insert(0, os.path.abspath('./detectron2'))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 1)) (1.23.3)\n",
      "Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 2)) (4.6.0.66)\n",
      "Requirement already satisfied: loguru in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 3)) (0.6.0)\n",
      "Collecting scikit-image\n",
      "  Using cached scikit_image-0.20.0-cp310-cp310-macosx_12_0_arm64.whl (12.7 MB)\n",
      "Requirement already satisfied: scikit-learn in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 5)) (1.1.2)\n",
      "Requirement already satisfied: tqdm in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 6)) (4.64.1)\n",
      "Requirement already satisfied: torchvision>=0.10.0 in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 7)) (0.14.0)\n",
      "Requirement already satisfied: Pillow in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 8)) (9.2.0)\n",
      "Collecting thop\n",
      "  Using cached thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)\n",
      "Collecting ninja\n",
      "  Using cached ninja-1.11.1-py2.py3-none-macosx_10_9_universal2.macosx_10_9_x86_64.macosx_11_0_arm64.macosx_11_0_universal2.whl (270 kB)\n",
      "Requirement already satisfied: tabulate in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 11)) (0.9.0)\n",
      "Requirement already satisfied: tensorboard in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 12)) (2.12.0)\n",
      "Collecting lap\n",
      "  Using cached lap-0.4.0.tar.gz (1.5 MB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: motmetrics in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 14)) (1.4.0)\n",
      "Collecting filterpy\n",
      "  Using cached filterpy-1.4.5.zip (177 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: h5py in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 16)) (3.7.0)\n",
      "Requirement already satisfied: matplotlib in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 17)) (3.6.1)\n",
      "Requirement already satisfied: scipy in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 18)) (1.9.2)\n",
      "Collecting prettytable\n",
      "  Using cached prettytable-3.6.0-py3-none-any.whl (27 kB)\n",
      "Collecting easydict\n",
      "  Using cached easydict-1.10.tar.gz (6.4 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: pyyaml in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 22)) (5.1)\n",
      "Requirement already satisfied: yacs in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 23)) (0.1.8)\n",
      "Requirement already satisfied: termcolor in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/requirements.txt (line 24)) (2.1.1)\n",
      "Collecting gdown\n",
      "  Using cached gdown-4.6.4-py3-none-any.whl (14 kB)\n",
      "Collecting onnx==1.8.1\n",
      "  Using cached onnx-1.8.1.tar.gz (5.2 MB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 118, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(config_settings)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-build-env-uy8cwg0w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 338, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return self._get_build_requires(config_settings, requirements=['wheel'])\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-build-env-uy8cwg0w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 320, in _get_build_requires\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-build-env-uy8cwg0w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 484, in run_setup\n",
      "  \u001b[31m   \u001b[0m     super(_BuildMetaLegacyBackend,\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-build-env-uy8cwg0w/overlay/lib/python3.10/site-packages/setuptools/build_meta.py\", line 335, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 75, in <module>\n",
      "  \u001b[31m   \u001b[0m AssertionError: Could not find \"cmake\" executable!\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "\u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n"
     ]
    }
   ],
   "source": [
    "!python3 -m pip install -r SMILEtrack/BoT-SORT/requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: thop in /opt/homebrew/lib/python3.10/site-packages (0.1.1.post2209072238)\n",
      "Requirement already satisfied: torch in /opt/homebrew/lib/python3.10/site-packages (from thop) (1.13.0)\n",
      "Requirement already satisfied: typing-extensions in /opt/homebrew/lib/python3.10/site-packages (from torch->thop) (4.4.0)\n",
      "Requirement already satisfied: lap in /opt/homebrew/lib/python3.10/site-packages (0.4.0)\n",
      "Requirement already satisfied: cython_bbox in /opt/homebrew/lib/python3.10/site-packages (0.1.3)\n",
      "Collecting faiss-cpu\n",
      "  Downloading faiss_cpu-1.7.3-cp310-cp310-macosx_11_0_arm64.whl (2.4 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.4/2.4 MB\u001b[0m \u001b[31m41.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: faiss-cpu\n",
      "Successfully installed faiss-cpu-1.7.3\n"
     ]
    }
   ],
   "source": [
    "!python3 -m pip install thop\n",
    "!python3 -m pip install lap\n",
    "!python3 -m pip install cython_bbox\n",
    "!python3 -m pip install faiss-cpu"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: matplotlib in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 1)) (3.6.1)\n",
      "Requirement already satisfied: scipy in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 2)) (1.9.2)\n",
      "Requirement already satisfied: Pillow in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 3)) (9.2.0)\n",
      "Requirement already satisfied: numpy in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 4)) (1.23.3)\n",
      "Collecting prettytable\n",
      "  Using cached prettytable-3.6.0-py3-none-any.whl (27 kB)\n",
      "Collecting easydict\n",
      "  Using cached easydict-1.10.tar.gz (6.4 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: scikit-learn in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 7)) (1.1.2)\n",
      "Requirement already satisfied: pyyaml in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 8)) (5.1)\n",
      "Requirement already satisfied: yacs in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 9)) (0.1.8)\n",
      "Requirement already satisfied: termcolor in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 10)) (2.1.1)\n",
      "Requirement already satisfied: tabulate in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 11)) (0.9.0)\n",
      "Requirement already satisfied: tensorboard in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 12)) (2.12.0)\n",
      "Requirement already satisfied: opencv-python in /opt/homebrew/lib/python3.10/site-packages (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 13)) (4.6.0.66)\n",
      "Collecting gdown\n",
      "  Using cached gdown-4.6.4-py3-none-any.whl (14 kB)\n",
      "Collecting faiss-gpu\n",
      "  Using cached faiss-gpu-1.7.1.post2.tar.gz (40 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h\u001b[33m  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.\u001b[0m\u001b[33m\n",
      "\u001b[0mDiscarding \u001b[4;34mhttps://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz (from https://pypi.org/simple/faiss-gpu/)\u001b[0m: \u001b[33mRequested faiss-cpu from https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 20)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'\u001b[0m\n",
      "  Using cached faiss-gpu-1.7.1.post1.tar.gz (41 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h\u001b[33m  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.\u001b[0m\u001b[33m\n",
      "\u001b[0mDiscarding \u001b[4;34mhttps://files.pythonhosted.org/packages/39/8d/b62bc92c8dd4b2a99d4a06b8804280f6445748b6d698eabb037e111080c7/faiss-gpu-1.7.1.post1.tar.gz (from https://pypi.org/simple/faiss-gpu/)\u001b[0m: \u001b[33mRequested faiss-cpu from https://files.pythonhosted.org/packages/39/8d/b62bc92c8dd4b2a99d4a06b8804280f6445748b6d698eabb037e111080c7/faiss-gpu-1.7.1.post1.tar.gz (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 20)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'\u001b[0m\n",
      "  Using cached faiss-gpu-1.7.1.tar.gz (40 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h\u001b[33m  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.\u001b[0m\u001b[33m\n",
      "\u001b[0mDiscarding \u001b[4;34mhttps://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz (from https://pypi.org/simple/faiss-gpu/)\u001b[0m: \u001b[33mRequested faiss-cpu from https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 20)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'\u001b[0m\n",
      "  Using cached faiss-gpu-1.7.0.tar.gz (34 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h\u001b[33m  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.\u001b[0m\u001b[33m\n",
      "\u001b[0mDiscarding \u001b[4;34mhttps://files.pythonhosted.org/packages/63/15/289ecf5d23f209c4c6f2f5f4db1d2b4a2be22d1fc49619354363e9367c19/faiss-gpu-1.7.0.tar.gz (from https://pypi.org/simple/faiss-gpu/)\u001b[0m: \u001b[33mRequested faiss-cpu from https://files.pythonhosted.org/packages/63/15/289ecf5d23f209c4c6f2f5f4db1d2b4a2be22d1fc49619354363e9367c19/faiss-gpu-1.7.0.tar.gz (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 20)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'\u001b[0m\n",
      "  Using cached faiss-gpu-1.6.5.tar.gz (28 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h\u001b[33m  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.\u001b[0m\u001b[33m\n",
      "\u001b[0mDiscarding \u001b[4;34mhttps://files.pythonhosted.org/packages/9c/27/3477c856ea3d678619c33ae72f89ede4fbe08e9c5ba3b89a5feb3d9938b0/faiss-gpu-1.6.5.tar.gz (from https://pypi.org/simple/faiss-gpu/)\u001b[0m: \u001b[33mRequested faiss-cpu from https://files.pythonhosted.org/packages/9c/27/3477c856ea3d678619c33ae72f89ede4fbe08e9c5ba3b89a5feb3d9938b0/faiss-gpu-1.6.5.tar.gz (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 20)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'\u001b[0m\n",
      "  Using cached faiss-gpu-1.6.4.post2.tar.gz (25 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h\u001b[33m  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.\u001b[0m\u001b[33m\n",
      "\u001b[0mDiscarding \u001b[4;34mhttps://files.pythonhosted.org/packages/7d/00/b3aaad408a44e4f5d87ebfcd75d0b14eeaed9fe9bc7a9f5e185ff1d503d6/faiss-gpu-1.6.4.post2.tar.gz (from https://pypi.org/simple/faiss-gpu/)\u001b[0m: \u001b[33mRequested faiss-cpu from https://files.pythonhosted.org/packages/7d/00/b3aaad408a44e4f5d87ebfcd75d0b14eeaed9fe9bc7a9f5e185ff1d503d6/faiss-gpu-1.6.4.post2.tar.gz (from -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt (line 20)) has inconsistent name: expected 'faiss-gpu', but metadata has 'faiss-cpu'\u001b[0m\n",
      "  Using cached faiss-gpu-1.6.4.tar.gz (3.4 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[7 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m running egg_info\n",
      "  \u001b[31m   \u001b[0m creating /private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-pip-egg-info-irv1si7q/faiss_cpu.egg-info\n",
      "  \u001b[31m   \u001b[0m writing /private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-pip-egg-info-irv1si7q/faiss_cpu.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m writing dependency_links to /private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-pip-egg-info-irv1si7q/faiss_cpu.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m writing top-level names to /private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-pip-egg-info-irv1si7q/faiss_cpu.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m writing manifest file '/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-pip-egg-info-irv1si7q/faiss_cpu.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m error: package directory '/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-install-w39mjfmx/faiss-gpu_64c04ddfa16d435299c8fe177e9a8756/faiss/faiss/python' does not exist\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n"
     ]
    }
   ],
   "source": [
    "!python3 -m pip install -r SMILEtrack/BoT-SORT/fast_reid/docs/requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/DiffusionTrack.py\", line 40, in <module>\n",
      "    from tracker.bot_sort import BoTSORT\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/SMILEtrack/BoT-SORT/tracker/bot_sort.py\", line 11, in <module>\n",
      "    from fast_reid.fast_reid_interfece import FastReIDInterface\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/SMILEtrack/BoT-SORT/fast_reid/fast_reid_interfece.py\", line 11, in <module>\n",
      "    from fast_reid.fastreid.engine import DefaultTrainer, default_argument_parser, default_setup, launch\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/SMILEtrack/BoT-SORT/fast_reid/fastreid/engine/__init__.py\", line 13, in <module>\n",
      "    from .hooks import *\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/SMILEtrack/BoT-SORT/fast_reid/fastreid/engine/hooks.py\", line 16, in <module>\n",
      "    from fast_reid.fastreid.evaluation.testing import flatten_results_dict\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/SMILEtrack/BoT-SORT/fast_reid/fastreid/evaluation/__init__.py\", line 4, in <module>\n",
      "    from .testing import print_csv_format, verify_results\n",
      "  File \"/Users/gabrielfiastre/Github/DiffusionTrack/SMILEtrack/BoT-SORT/fast_reid/fastreid/evaluation/testing.py\", line 5, in <module>\n",
      "    from collections import Mapping, OrderedDict\n",
      "ImportError: cannot import name 'Mapping' from 'collections' (/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)\n"
     ]
    }
   ],
   "source": [
    "!python3 DiffusionTrack.py --config-file configs/diffdet.mot.swinbase.yaml --input \"datasets/mot/train/*FRCNN/img1\" --output \"output_PRIOR/CrowdHuman_random\" --confidence-threshold 0.1 --opts MODEL.WEIGHTS output/model_0054999.pth MODEL.DiffusionDet.SAMPLE_STEP 8 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pytorch\n",
      "  Downloading pytorch-1.0.2.tar.gz (689 bytes)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hBuilding wheels for collected packages: pytorch\n",
      "  Building wheel for pytorch (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[6 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-install-d5qxp9hi/pytorch_75f8c6bfb30f4ecbae925a877b90249d/setup.py\", line 15, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(message)\n",
      "  \u001b[31m   \u001b[0m Exception: You tried to install \"pytorch\". The package named for PyTorch is \"torch\"\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for pytorch\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for pytorch\n",
      "Failed to build pytorch\n",
      "Installing collected packages: pytorch\n",
      "  Running setup.py install for pytorch ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mRunning setup.py install for pytorch\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[6 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/fs/pl0bq7c97j7ddng3nfms3k840000gn/T/pip-install-d5qxp9hi/pytorch_75f8c6bfb30f4ecbae925a877b90249d/setup.py\", line 11, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(message)\n",
      "  \u001b[31m   \u001b[0m Exception: You tried to install \"pytorch\". The package named for PyTorch is \"torch\"\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mlegacy-install-failure\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while trying to install package.\n",
      "\u001b[31m╰─>\u001b[0m pytorch\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for output from the failure.\n"
     ]
    }
   ],
   "source": [
    "!python3 -m pip install pytorch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[32m[03/18 01:24:27 DiffTrack]: \u001b[0mArguments: Namespace(path='../MOT17/train/MOT17-02-FRCNN/img1/', output_dir='DEMO', save_det=True, save_frames=False, det_folder='', config_file='DiffusionDet/configs/diffdet.mot.swinbase.yaml', confidence_threshold=0.1, class_id=0, opts=['MODEL.WEIGHTS', 'DiffusionDet/models/model_0064999.pth', 'MODEL.DiffusionDet.SAMPLE_STEP', '8'], device='mps', with_reid=False, benchmark='MOT17', eval='test', f=None, c=None, ablation=False, experiment_name='DEMO', default_parameters=False, conf=None, nms=None, tsize=None, fp16=False, fuse=False, track_high_thresh=0.6, track_low_thresh=0.1, new_track_thresh=0.7, track_buffer=30, match_thresh=0.8, aspect_ratio_thresh=1.6, min_box_area=10, cmc_method='none', fast_reid_config='fast_reid/configs/MOT17/sbs_S50.yml', fast_reid_weights='pretrained/mot17_sbs_S50.pth', proximity_thresh=0.5, appearance_thresh=0.25)\n",
      "\u001b[32m[03/18 01:24:27 DiffTrack]: \u001b[0mDevice : mps\n",
      "\u001b[32m[03/18 01:24:27 DiffTrack]: \u001b[0mOutput tracked detections will be stored in DEMO\n",
      "------------------------------------------------------------------------------------------------------------------------------------------------------\n",
      "                                              Processing video img1 (1/1)                                               \n",
      "------------------------------------------------------------------------------------------------------------------------------------------------------\n",
      "\u001b[32m[03/18 01:24:27 DiffTrack.DiffusionDet]: \u001b[0mBeginning detection...\n",
      "BABA\n",
      "  0%|                                                   | 0/600 [00:00<?, ?it/s]avant\n"
     ]
    }
   ],
   "source": [
    "!python3 demo.py '../MOT17/train/MOT17-02-FRCNN/img1/' --device mps --output-dir \"DEMO\" --config-file DiffusionDet/configs/diffdet.mot.swinbase.yaml --opts MODEL.WEIGHTS DiffusionDet/models/model_0064999.pth MODEL.DiffusionDet.SAMPLE_STEP 8 "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
